import '../styles/globals.css'
import {getServerSession} from "next-auth";
import Sidebar from "../components/sidebar";
import SessionProvider from "../components/sessionProvider";
import {authOptions} from "../pages/api/auth/[...nextauth]";
import Login from "../components/login";
import ClientProvider from "../components/clientProvider";


export const metadata = {
  title: 'ChatGPT',
  description: 'Generated by g-hack',
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
      <SessionProvider session={session}>
          {!session  ? (
            <Login/>
          ):(
              <div className="flex">
                  {/*  sidebar*/}
                  <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                      <Sidebar/>

                  </div>
                  {/*  client provider notifications*/}
                  <ClientProvider/>
                  <div className="bg-[#343541] text-white flex-1">
                      {children}
                  </div>
              </div>
          )}

      </SessionProvider>
      </body>
    </html>
  )
}
